# Generated by Django 6.0.6 on 2026-06-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=12, unique=True)),
                ('customer_type', models.IntegerField(choices=[(0, 'Физическое лицо'), (1, 'Индивидуальный предприниматель'), (2, 'Юридическое лицо')], default=0)),
                ('name', models.CharField(max_length=255)),
                ('customer_name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=255)),
                ('contact_number', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Executors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('registration_type', models.IntegerField(choices=[(0, 'ГПХ'), (1, 'НПД')], default=0)),
                ('tax_rate', models.IntegerField()),
                ('unit', models.IntegerField(choices=[(0, 'Часы'), (1, 'Дни'), (2, 'Полная стоимость')], default=0)),
                ('unit_cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1024)),
                ('purchase_type', models.IntegerField(choices=[(0, 'Собственное'), (1, 'В аренде')], default=0)),
                ('operating_cost', models.IntegerField()),
                ('unit', models.IntegerField(choices=[(0, 'Часы'), (1, 'Дни'), (2, 'Полная стоимость')], default=0)),
                ('unit_cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('salary', models.IntegerField()),
                ('tax_rate', models.IntegerField()),
            ],
        ),
    ]
