# Generated by Django 6.0.6 on 2026-06-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registries', '0002_alter_customers_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='description',
            field=models.TextField(max_length=1024),
        ),
    ]
