# Generated by Django 6.0.6 on 2026-06-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registries', '0003_alter_hardware_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executors',
            name='tax_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='operating_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='staff',
            name='tax_rate',
            field=models.IntegerField(default=0),
        ),
    ]
