# Generated by Django 6.0.6 on 2026-06-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(default='Компания', max_length=255),
        ),
    ]
