# Generated by Django 6.0.6 on 2026-06-18 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2026, 6, 18, 12, 9, 4, 473038)),
        ),
        migrations.AddField(
            model_name='projectresource',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2026, 6, 18, 12, 9, 4, 473548)),
        ),
    ]
