# Generated by Django 6.0.6 on 2026-06-18 09:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_start_date_projectresource_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='projectresource',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
