# Generated by Django 6.0.6 on 2026-06-17 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workspace',
            options={'permissions': [('can_manage_projects', 'Может управлять проектами')]},
        ),
    ]
