# Generated by Django 6.0.6 on 2026-06-15 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_workspace_workspacepermissions_delete_project_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_workspaces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='users',
            field=models.ManyToManyField(related_name='workspaces', through='workspace.WorkspacePermissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
