# Generated by Django 6.0.6 on 2026-06-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_alter_workspace_admin_alter_workspace_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
