# Generated by Django 6.0.6 on 2026-06-09 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
